name: tus_client
description: A tus client for dart allowing resumable uploads using the tus protocol.
version: 1.0.0
homepage: https://github.com/jjmutumi/tus_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cross_file_dart:
    git: https://github.com/redsolver/cross_file_dart.git
  http: ^0.13.0
  path: ^1.7.0

dev_dependencies:
  mockito: ^5.0.3
  build_runner: ^1.11.0
